### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by d-sel** [UBC-MDS/instaeda_R#1]
- [x] Create repo/project
- [x] Add MIT license
- [x] Add Code of Conduct with `usethis::use_code_of_conduct`
- [x] add team members to DESCRIPTION
   - [x] input contributor e-mails in DESCRIPTION doc (@roycezhou )
- [x] Add CONTRIBUTING.md with `usethis::use_tidy_contributing()`
- [x] Add README with sections:
   - [x] summary paragraph
   - [x] list of functions
   - [x] R ecosystem paragraph
- [x] function specs
   - [x] `plot_intro`
   - [x] `plot_corr`
   - [x] `divide_and_fill`
   - [x] `plot_basic_distributions`
